### ISSUE TITLE
Internal links are broken in the landing page

### ISSUE THREAD

**Issue by miscco** [NVIDIA/libcudacxx#4]
Moving the readme to `/docs` broke the internal links to `api.md` and `synchronization_library.md` because at the landing page it is missing the additional redirection to `/docs` (It seems to assume that the file is included as is)

I am not 100% sure what the correct fix is, as adding `/docs` to the internal links will break `/docs/readme.md` rather than the landing page

**Comment by miscco** [comment]
To be more specific opening the `synchronization_library` link at the landing page of the repo leads one to the non existing page
```
https://github.com/NVIDIA/libcudacxx/blob/main/api/synchronization_library.md
```

The same link opened in `/docs/readme.md` opens up this link which works
```
https://github.com/NVIDIA/libcudacxx/blob/main/docs/api/synchronization_library.md
```

**Comment by brycelelbach** [comment]
Gotcha. So, here's what happened:

We wanted our documentation to be in Markdown, in the main source tree, and rendering nicely as Markdown both on GitHub's repository browser and on GitHub Pages. We wanted to avoid duplication wherever possible, to avoid the number of places that need to be updated as the codebase evolves and minimize the chance of stale documentation.

To that end, we are set up to use GitHub Pages, where the Pages content comes from the `docs/` directory on the `main` branch. Documentation-like files that typically live in the root of a repository and are treated specially by GitHub, `README.md`, `CONTRIBUTING.md`, and `CODE_OF_CONDUCT.md`, are just symbolic links to files in `docs/` so that we can use the same source files for GitHub Pages.

We use a few plugins to make this work; `jekyll-optional-front-matter` lets us put all the jekyll metadata in a single `.yml` file, so that the Markdown itself renders nicely on GitHub's file viewer. `jekyll-readme-index` uses `readme.md` as the default landing page that jekyll expects. [`jekyll-relative-links`](https://github.com/benbalter/jekyll-relative-links) lets us link to files as `.md` instead of the generated `.html`, so that links /should/ work on both GitHub's file viewer and on GitHub Pages.

I'm fairly certain the links are not working in the main repo README because its' a symlink. When viewing [the same file (i.e. the one the symlink points to) in `docs/`](https://github.com/NVIDIA/libcudacxx/blob/main/docs/readme.md), the links work fine. 

I think the best solution is for us to just hard code the links in the README to not be relative, but to point to the full GitHub pages links; that should work for both viewing on GitHub, and viewing on GitHub Pages.
