### ISSUE TITLE
Does `cuda::std::complex` have opt-in for simplified complex math

### ISSUE THREAD

**Issue by fkallen** [NVIDIA/libcudacxx#473]
Multiplication of `cuda::std::complex` includes checking for overflow which makes the SASS really large compared to cuComplex' `cuCmul`, and requires more registers. See https://godbolt.org/z/K11j5a1z8

On GCC with the standard c++ library, one could pass `-fcx-limited-range` to allow for simplified mult, div, and abs, but this does not seem to work with NVCC and libcu++. 
Is there a way to enable simplified complex math for `cuda::std::complex` ?

**Comment by miscco** [comment]
Hi @fkallen yes there is partial support for this since a few months, when we enabled constexpr complex. 

You can define `LIBCUDACXX_ENABLE_SIMPLIFIED_COMPLEX_MULTIPLICATION` to remove the normalization from multiplication.

Now that I am looking at the code, I find that we should have also added that to division.

**Comment by miscco** [comment]
I will open a PR to also allow for simplified multiplication

**Comment by miscco** [comment]
@fkallen we have merged an additional escape hatch also for complex division.

You can define `LIBCUDACXX_ENABLE_SIMPLIFIED_COMPLEX_OPERATIONS` to remove the canonicalization of both division and multiplication.

For a more fine grained approach there are also `LIBCUDACXX_ENABLE_SIMPLIFIED_COMPLEX_MULTIPLICATION` and `LIBCUDACXX_ENABLE_SIMPLIFIED_COMPLEX_DIVISION`
